name: VanillaCore
main: com.pdev.vanillacore.Main
description: The VanillaRealms Core Plugin
version: 1.0.0
author: pdev
depend: [LuckPerms]
api-version: 1.13

commands:
  message:
    description: The message command
    usage: /<command>
    aliases: [m, whisper, msg, w]
  reply:
    description: The reply command
    usage: /<command>
    aliases: [r]
  broadcast:
    description: The broadcast command
    usage: /<command>
    aliases: [bc]
    permission: vanillacore.broadcast
  socialspy:
    description: The social spy command
    usage: /<command>
    aliases: [sspy, ss]
    permission: vanillacore.socialspy
  commandspy:
    description: The command spy command
    usage: /<command>
    aliases: [cspy, cs]
    permission: vanillacore.commandspy

permissions:
  vanillacore.commandspy.list:
    description: See the list of active command spies
    default: op
  vanillacore.bypass.commandspy:
    description: Bypasses this players commands being sent to command spies
  vanillacore.bypass.move:
    description: Bypass having to move to execute commands & chat
    default: op
  vanillacore.socialspy.list:
    description: See the list of active social spies
    default: op
  vanillacore.bypass.socialspy:
    description: Bypass messages showing up in social spy
    default: op
  vanillacore.bypass.ascii:
    description: Bypass ascii characters being blocked in your chat messages
    default: op
  vanillacore.bypass.antiad:
    description: Bypass the block on sending links and IPs in your chat messages
    default: op
  vanillacore.staff:
    description: Counted as a staff member
    default: op
  vanillacore.chat.format:
    description: Allows the user to use colors and formats in chat
    default: op